### ISSUE TITLE
functions name consistency

### ISSUE THREAD

**Issue by n0vember** [pgrange/bash_unit#35]
Assert functions name should either be infinitive+infinitive (ex : assert_fail) or noun+conjugation (ex: assert_fails). It is mixed (assert_fail, but assert_equals) and leads to errors. As we can not set for one or the other in order to preserve backwards compatibility, I propose to have both.

**Comment by pgrange** [comment]
I would say that assert is for the verb, not the noun which would be assertion. 

Si it is supposed to be something like "we assert that this expression equals another"  or "we assert that this expression fails" 

So I agree that assert_fail should be assert_fails instead. 

I also agree that we have to maintain existing assertion functions. 

I suppose you opened the issue because of a mistake you made often in your code. Just out of curiosity, would you mind explaining which one you regularly "misspelled"?

**Comment by n0vember** [comment]
Problem was assert_fail at first. I always used to write assert_fails and then correct it. But then, as I knew there was a thing about this, I started to write assert_equal, thinking there was no 's' anywhere.

In fact, I could have get used to it if they had all been the same way :)
