### ISSUE TITLE
Is the GNUv3 licence compatible with the "enterprise" aspiration?

### ISSUE THREAD

**Issue by keithy** [pgrange/bash_unit#48]
I myself tend to use the MIT Licence, but I think that your selection of GNUv3 makes this unusable in an enterprise environment. Can you reassure me?

K.

**Comment by pgrange** [comment]
Hi @keithy and thank you for your interest in bash_unit.

bash_unit is licenced under the GPLv3. I can not see any issue in using GPLv3 software in an enterprise environment, on the contrary.

But it may depend on how you intend to use and distribute the software and, on that part, only you can answer after a thorough (and a little boring) examination of GPLv3. The [GPLv3 faq](https://www.gnu.org/licenses/gpl-faq.en.html) may help you on this.

In this particular case of bash_unit, bash_unit being a bash unit testing library and software, I would consider two types of source code you write:
1. test code which relies on the bash_unit testing functions;
2. code under test which is called _from outside_ by bash_unit.

For the first category of code, your test code, I believe GPLv3 applies to it since we may consider this code to be _linked_ with an depend on bash_unit testing library... but I may be wrong, I am not a jurist or licence expert, this is only my interpretation.

For the second category of code, your code under test, I can not see any reason why GPLv3 would apply on your code. This code under test is not linked in any way with any bash_unit code and it is bash_unit which, from the outside, launches this code but this code can also be launched in another context. So on this part, I am pretty sure you can choose whatever licence you want.

Regards,

**Comment by pgrange** [comment]
That was my answer on the _technical_ side.

On a more _philosophical_ side, this question has already been raised in #9 and I am worried. Is there some kind of _do not use GPL this is evil and not compliant with corporations_ campaign out there ? ;)

In my personal  case, I chose GPLv3 because of my belief in free software more than just open source.

MIT, BSD, WTFPL are more or less equivalent with a public licence granting the person who gains access to the source to do what she wants with, without any constraints. That is OK but I believe, especially in a corporate world, that GPLv3 is fairer in the way that it allows the person who gains access to the source to do what she wants with, in the condition that she grants the same right to her customers.

I believe, especially in a corporate world, GPLv3 is more compliant with _enterprise aspiration_ than other permissive licences since it may protect your company against at least two issues.

One issue may be a concurrent using your software in an unfair way forbidding you or his customers to enjoy any improvement made on your work.

Another situation might be with a customer claiming intellectual property on your software because of a contract issue. Some small line stating _everything you do belongs to me_. If the work done for this customer is based on your previous work and you did not see that small line, I believe you will have more options when negotiating this situation if this previous work was protected by GPLv3 rather than MIT.

**Comment by pgrange** [comment]
May be I'll just share a BTC address and see if I can share a _pgrange licensed_ version of bash_unit ;)

Joke aside, I close this issue since it does not seem there is anymore activity to come here.

Regards,

**Comment by jlisee** [comment]
This is a great small elegant library, sorry common on this old issue but I also think raw GPLv3 is not enterprise ready and was curious.

Is there a reason you did not go with the LGPLv3 here?  For enterprise use lawyers are allergic to any internal code being bound by the GPL, but generally OK with careful usage and contribution to LGPL software.  I think the worry is that you now have GPLv3 code in your tree so the following use case are worrisome:

 - You can no longer copy/reference your GPLv3 test code when working on other parts of the software, because that would make them GPLv3
 -  The interpretation of the GPL may change causing more code in your product to become GPL
