### ISSUE TITLE
functions returning strings with spaces

### ISSUE THREAD

**Issue by Httqm** [pgrange/bash_unit#52]
Not sure whether this is a bug of a misuse (aka "feature") : 

let's consider a function returning a string having space(s) : "hello world".
I'd like to test this function and make sure I actually receive the full function output.
However, what's received by the testing facility is the string up to the space character ("hello"), so the test fails.

You can reproduce this with
`./bash_unit tests/test_spaces.sh`
from https://github.com/Httqm/bash_unit/tree/spaces

**Comment by pgrange** [comment]
Hi @Httqm,

Thanks for using bash_unit, always a pleasure to meet new users. 

For your problem, it is the way bash works. It first evaluates what is inside `$()` then calls `assert_equals`. So if your function outputs two strings, then `assert_equals` will receive two separate parameters (because bash uses space to identify separate parameters). Hence the behavior you observe. 

You can solve this by placing your function call between `"` so that bash knows it has to deal with that as a single parameter.

```
test_functionThatReturnsAStringWithSpaces() {
	assert_equals 'hello world' "$(functionThatReturnsAStringWithSpaces) "
	}
```

**Comment by pgrange** [comment]
Hope my comment was usefull. I close the issue but do not hesitate to reopen if needed.
Regards,
