### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by anoother** [pgrange/bash_unit#55]
Is it possible for a new version to be released, based on the latest changes?

**Comment by pgrange** [comment]
Hi,
Thank you for using bash_unit.
Sorry for the totally insane delay.

If you are refering to a new Debian release, unfortunately I don't support it anymore. See
https://github.com/pgrange/bash_unit/issues/56

Otherwise, I just released a new 1.7.0 version here. See https://github.com/pgrange/bash_unit/releases
